### ISSUE TITLE
pet_wolves does not have the wolves sitting properly [Fabric, 1.21.3]

### ISSUE THREAD

**Issue by KristenStuffs** [jack-zisa/lucky_block#4]
pet_wolves' wolves appear sitting, but are still able to move. This is likely an error with the NBT, if I had to guess it is with Sitting which should be 1b instead of True.

**Comment by jack-zisa** [comment]
Yeah, ive seen this happening. The issue is that in the game code, when you right-click a wolf (or other pet) to sit, it stops their movement. The Sitting NBT tag doesnt do this itself, oddly enough. With the upcoming function system, Ill have a custom function for sitting pets to fix this.
